-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.address
(
    id integer PRIMARY KEY,
    building_number character varying(10) COLLATE pg_catalog."default",
    street_name character varying(50) COLLATE pg_catalog."default",
    post_code character varying(10) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.cart_item
(
    id character varying(50) COLLATE pg_catalog."default" PRIMARY KEY,
    item_id character varying(50) COLLATE pg_catalog."default",
    user_id character varying(50) COLLATE pg_catalog."default",
    quantity integer,
    total_price_per_item integer,
    order_id "char"
);

CREATE TABLE IF NOT EXISTS public.items
(
    id character varying(50) COLLATE pg_catalog."default" PRIMARY KEY,
    name character varying(50) COLLATE pg_catalog."default",
    quantity integer,
    description character varying(200) COLLATE pg_catalog."default",
    price integer,
    status character varying(50) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id character varying(50) COLLATE pg_catalog."default" PRIMARY KEY,
    user_id character varying(50) COLLATE pg_catalog."default",
    total_quantity integer,
    total_price integer,
    status "char" NOT NULL
);

CREATE TABLE IF NOT EXISTS public.shop
(
    id character varying(50) COLLATE pg_catalog."default" PRIMARY KEY,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(50) COLLATE pg_catalog."default",
    phone_nr integer,
    address_id integer,
    capital integer
);

CREATE TABLE IF NOT EXISTS public.users
(
    id character varying(50) COLLATE pg_catalog."default" PRIMARY KEY,
    address_id integer NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    surname character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(50) COLLATE pg_catalog."default",
    password character varying(50) COLLATE pg_catalog."default" NOT NULL
);

ALTER TABLE IF EXISTS public.cart_item
    ADD CONSTRAINT cart_item_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.items (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cart_item
    ADD CONSTRAINT cart_item_item_id_fkey1 FOREIGN KEY (item_id)
    REFERENCES public.items (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cart_item
    ADD CONSTRAINT cart_item_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_user_id_fkey1 FOREIGN KEY (user_id)
    REFERENCES public.users(id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

END;